--- 
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations: 
    datadoghq.com/site: datadoghq.com
    datadoghq.com/dashboard-url: https://app.datadoghq.com/dashboard/3v7-fpx-rrh/carrier-api-facade-k8-stats?tv_mode=true&from_ts=1633845574030&to_ts=1633931974030&live=true
    datadoghq.com/graph-token: fcd694139d5d08846d8f22372b38841da0b10e766e8d08225951ff0a80a148de
    lighthouse.com/website-url: "/docs/auth/auth-backend-classes"
    jenkins.io/github-folder: "SQE-Tracking/cross_browser_tests/"
    sonarqube.org/project-key: "narvar:whatsapp-service"
    backstage.io/techdocs-ref: "url:https://github.com/narvar/Retailer-notification-preferences/tree/PRD-292"
    snyk.io/org-name: BalaNarvar
    snyk.io/project-ids: b0eefcb6-88b1-4a46-89ed-d2f718b5a35c
    cloud.google.com/function-ids: projects/project-name/locations/region-name/functions/function-name
    jira/project-key: MSG
    #datadoghq.com/site: https://app.datadoghq.com/monitors/26168411
    narvar-datadog/monitor: "https://app.datadoghq.com/monitors/26168411,https://app.datadoghq.com/monitors/26168623,https://app.datadoghq.com/monitors/19787557,https://app.datadoghq.com/monitors/19494724,https://app.datadoghq.com/monitors/12151058,testing without space"
    narvar-datadog/dashboard: Atlas-Api Metrics|https://app.datadoghq.com/dashboard/ji3-e5z-bsw/ds---atlas-api-metrics?from_ts=1628741448028&to_ts=1628745048028&live=true, Carrier Queue Processor Metrics|https://app.datadoghq.com/dashboard/kfw-h4x-3kj/ds---carrier-queue-processor-metrics?from_ts=1629441313421&to_ts=1629444913421&live=true
    narvar-noflake/url: "https://noflake.narvar.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo4LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE2NH19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=, https://noflake.narvar.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOm51bGx9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319, https://noflake.narvar.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOm51bGx9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319"
    narvar-grafana/dashboard: "http://pulsar-prod01.narvar.com:3000/d/Ypa0B5eWk/overview?orgId=1&refresh=1m, http://pulsar-prod01.narvar.com:3000/d/b2w0sy-ik/functions-metrics?orgId=1&from=now-6h&to=now&var-cluster=All&var-namespace=prod01%2Fmessaging&var-function=rulespulsarreader, http://pulsar-prod01.narvar.com:3000/d/p0LQ5r7Mz/topic-metrics?orgId=1&refresh=5s&from=now-2d&to=now&var-cluster=All&var-namespace=prod01%2Fdata-services&var-topic=persistent:%2F%2Fprod01%2Fdata-services%2Fatlas-output-partition-0&var-topic=persistent:%2F%2Fprod01%2Fdata-services%2Fatlas-output-partition-1&var-topic=persistent:%2F%2Fprod01%2Fdata-services%2Fatlas-output-partition-2&var-topic=persistent:%2F%2Fprod01%2Fdata-services%2Fatlas-output-partition-3" 
    narvar-speca/url: https://narvar.atlassian.net/wiki/spaces/TESTENG/pages/1014595727/ADA+Test+For+Messaging+Emailss
    narvar-wiki/url: "https://app.datadoghq.com/monitors/26168411 ,https://app.datadoghq.com/monitors/26168623 , https://app.datadoghq.com/monitors/19787557 ,https://app.datadoghq.com/monitors/19494724"
  links:
    - url: https://narvar.atlassian.net/wiki/spaces/TESTENG/pages/1014595727/ADA+Test+For+Messaging+Emailss
      title: ADA Links
      icon: confluence
  retoollinks:
    - url: https://retool-qa01.narvar.qa/apps/Returns/Picklist%20v2
      title: QA01 (Retool - Picklist)
    - url: https://retool-st01.narvar.qa/apps/Returns/Picklist%20v2
      title: ST01 (Retool - Picklist)
    - url: https://retool.narvar.com/apps/Returns/Picklist%20v2
      title: PROD (Retool - Picklist)
  runbooklinks:
    - url: https://narvar.atlassian.net/wiki/spaces/EN/pages/1205732146
      title: Carrier Facade Troubleshooting Runbook
    - url: https://narvar.atlassian.net/wiki/spaces/EN/pages/1205928198/Return+Carrier+Label+Troubleshooting+Runbook
      title: Return Carrier Label Troubleshooting Runbook
    - url: https://narvar.atlassian.net/wiki/spaces/EN/pages/1987185979
      title: Carrier Scheduler Manager Troubleshooting Runbook
    - url: https://narvar.atlassian.net/wiki/spaces/EN/pages/1997701456/Fiji+Config+Service+Troubleshooting+Runbook
      title: Fiji Config Service Troubleshooting Runbook
    - url: https://narvar.atlassian.net/wiki/spaces/EN/pages/2015035837
      title: Capri Troubleshooting Runbook
  description: Backstage-Testing5
  name: Bala-backstage5
  tags: 
    - java
    - python
spec: 
  lifecycle: experimental
  owner: bala Krishnan
  type: service
  system: messaging-system
