apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: capri-api
  description: This document covers the current APIs supported by Narvar's Intelligent
    Carrier Allocation Service. This is offered as part of Narvar Ship product and
    augments the APIs and settings provided as part of the Narvar Hub integration.
spec:
  type: openapi
  lifecycle: production
  owner: carriers
  system: capri
  definition: |
    openapi: 3.0.0
    info:
      title: Narvar Intelligent Carrier Allocation Service
      description: This document covers the current APIs supported by Narvar's Intelligent
        Carrier Allocation Service. This is offered as part of Narvar Ship product and
        augments the APIs and settings provided as part of the Narvar Hub integration.
      _postman_id: a9821849-87f4-4723-b62a-80e24d0f210d
      version: SLGv1
    servers:
      - url: https://api.narvar.com/v1
    paths:
      /shipping-labels:
        post:
          summary: Generate Carrier Shipping Label
          description: Generate shipping forward label from retailer to customer. The
            service abstracts all carrier logic and normalizes the API specification across
            multiple carriers.
          parameters:
            - name: "X-Narvar-Tracer-ID"
              in: "header"
              required: true
              type: "string"
              description: Tracer ID is used to trace the request, via logging.
            - name: X-Narvar-Experimental
              in: "header"
              required: true
              type: "string"
              description: when this header is set, experimental features are enabled on
                this API
            - name: Authorization
              in: "header"
              required: true
              type: "string"
              description: Bearer Token
            - in: body
              name: user
              description: The user to create.
          response:
          - status: '200'
            code: 200
          - status: Bad Request
            code: 400
          - status: Forbidden
            code: 403
          - status: Unauthorized
            code: 401
          - status: Unprocessable Entity
            code: 422
          - status: Too Many Requests
            code: 429
      /shipping-labels:
        get:
          summary: Retrieve Shipping Label by reference IDs
          description: Retrieves the previously generated labels based on identifiers
          parameters:
            - name: "id"
              in: "query"
              description: The UUID to uniquely identify a label. This is same id recieved as part of the `Label Generation API`"
              required: true
              type: "string"
            - name: "tracking_number"
              in: "query"
              description: "The tracking number assigned to in a label by the carrier. This is tracking number recieved as part of the `Label Generation API`"
              required: true
              type: "string"
            - name: "shipment_id"
              in: "query"
              description: "The opaque unique identifier sent as part of `Shipping Label Request` as part of the `Label Generation API`."
              required: true
              type: "string"
          response:
          - status: '200'
            code: 200
