apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: carrier-api-facade-api
  description: Shows list of API used in carrier-api-facade
spec:
  type: openapi
  lifecycle: production
  owner: carriers
  system: carrier-api-facade
  definition: |
    openapi: 3.0.0
    info:
      title: Carrier Facade API
      version: 1.0.0
    servers:
      - url: http://internal-d471ad54-qa01-carrierapifa-d865-1635686225.us-west-2.elb.amazonaws.com
      - url: http://internal-4d78fcee-qa02-carrierapifa-e94a-232005264.us-west-2.elb.amazonaws.com
    paths:
      /carrier/{carrierName}/tracking:
        get:
          tags:
            - default
          summary: Carrier Facade Tracking API
          description: This API is used to derive tracking information from a carrier
          parameters:
            - name: tracking_id
              in: query
              schema:
                type: integer
              example: '392501087608'
            - name: retailer
              in: query
              schema:
                type: string
              example: bedbathandbeyond
            - name: locale
              in: query
              schema:
                type: string
              example: fr
            - name: carrierName
              in: path
              type: string
              example: ftn
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /configuration/carrier_config/{carrierName}/{retailerName}:
        get:
          tags:
            - default
          summary: Carrier Configuration API
          description: Used to fetch carrier level configuration
          parameters:
            - name: retailerName
              in: path
              type: string
              example: bedbathandbeyond
            - name: carrierName
              in: path
              type: string
              example: ftn
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /carrier-alias/carrier:
        get:
          tags:
            - default
          summary: Carrier Alias API
          description: Used to fetch all stored aliases associated to a carrier
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /carrier-alias/retailer/{retailerName}:
        get:
          tags:
            - default
          summary: Carrier Alias with Retailer API
          description: Used to fetch carrier alias w.r.t a retailer
          parameters:
            - name: retailerName
              in: path
              type: string
              example: bedbathandbeyond
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /status-codes/mapping/{carrierName}:
        get:
          tags:
            - default
          summary: status mapping api
          parameters:
            - name: event_code
              in: query
              schema:
                type: integer
              example: '200'
            - name: carrierName
              in: path
              type: string
              example: ftn
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /status-codes/mappings/{carrierName}:
        get:
          tags:
            - default
          summary: source mappings API
          parameters:
            - name: source
              in: query
              schema:
                type: string
              example: API
            - name: carrierName
              in: path
              type: string
              example: ftn
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
      /carrier/{carrierName}/tracking-debug:
        get:
          tags:
            - default
          summary: Carrier Facade Tracking-Debug API
          description: This API is used to get debugging information from Carrier API, i.e, the
            original carrier response is appeneded to the original carrier tracking
            response.
          parameters:
            - name: tracking_id
              in: query
              schema:
                type: integer
              example: '392501087608'
            - name: retailer
              in: query
              schema:
                type: string
              example: bedbathandbeyond
            - name: locale
              in: query
              schema:
                type: string
              example: fr
            - name: carrierName
              in: path
              type: string
              example: ftn
          responses:
            '200':
              description: Successful response
              content:
                application/json: {}
