apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: raavi-api
  description: Shows list of API used in raavi
spec:
  type: openapi
  lifecycle: production
  owner: partnership
  system: messaging-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Raavi
      license:
        name: MIT
    servers:
      - url: http://internal-d471ad54-qa01-retailernoti-2790-1968814195.us-west-2.elb.amazonaws.com/swagger-ui/index.html#/
