apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: raavi-api
  description: Shows list of API used in raavi
spec:
  type: openapi
  lifecycle: production
  owner: partnership
  system: messaging-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.1
      title: Raavi
      license:
        name: MIT
    servers:
      - url: https://raavi.narvar.com/api/v1
    paths:
      /order:
        post:
          summary: Posting an order for raavi
          description: Passing Order detail
          produces:
          - "application/json"
          parameters:
          - in: "body"
            name: "body"
            description: "passing the payload"
            required: true
          responses:
            "200":
              description: "successful operation"
